### ISSUE TITLE
Snap to taxi routes

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#100]
**Current Situation / Problem**
Planes follow a direct path between 2 position (roughly) as reported by the channels. That makes them cut corners, which looks bad especially on the ground when leaving runways/taxiways for the shortest path to the next position.

**Suggested Solution**
Follow runways and taxiways In two complexities:
- snap positions onto the next line in a given max distance
- follow a path to the next position even if it includes to turn around a corner, which would need to be artificially inserted into the queue of positions.

This can be considered for
- auto-land: find exact landing spot
- normal land: position first on-ground position centered on runway
- taxiing: follow taxiways

**Benefits**
Ground movement will look much better.

**Additional context**
We are still bound by reality: We _have_ to be at the target position by a certain timestamp. To make up for extra distance speed will adjust.

**Todos**
- [x] Read `apt.dat`
    - [X] Airports (`1`)
    - [X] Runways (`100`)
    - [x] Taxiways (probably only the painted lines (`120`)
    - [X] Source: globally provided `apt.dat` files
    - [x] Source: local files in Custom Scenery directories
    - [x] For Custom Scenery files, consider `scenery_packs.ini` for order of processing of only enabled packages (this does contain `Custom Scenery/Global Airports`, too) 
- [X] Auto-Land: Find proper runway and land exactly
- [x] Normal landing: Snap on-runway position to center line
- [x] Taxiing
    - [x] Snap positions to center line
    - [x] Find shortes taxiway path between two positions and insert that path
    - [x] If no shortest path could be found leaving a runway to a taxiway, then insert turning points where lines meet. Implementation is by finding the geometric intersection of the center lines two adjacent positions are snapping to. This intersection may or may not be an actual taxi center line crossing point in the airport, but will still be better than cutting corners. ~(A fully fledged routing mechanism along the taxi center lines is not currently an option!)~

**Comment by TwinFan** [comment]
Implemented reading `apt.dat` file for airports and runways. For the moment just one of the globally provided ones, not yet additional ones from Custom Scenery. And not yet taxiways.
Runways considered for auto-land.
