### ISSUE TITLE
Start fetching tracking data while X-Plane initializes

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#113]
**Current Situation / Problem**
X-Plane takes ages for init...and then only LT starts requesting data.

**Suggested Solution**
We could use the time already for some request/reply. That doesn't eat much performance, is in separate threads...and when X-Plane is done we might already have valid data and can display planes right away.

**Benefits**
Faster startup.

**Additional context**
- [ ] Only if autostart is ON!
- [ ] verify that all other init is done, i.e. state is `STATE_ENABLED`.
- [ ] We must not create actual planes before drawing callbacks. So the point in time we now only start requesting data would be the point in time we start the first A/c maintenance and request AI planes.

**Comment by TwinFan** [comment]
Doesn't work as LT can't determine planes/cameras position before all X-Plane init is done. Can't implement.
