### ISSUE TITLE
Small "status field"

### ISSUE THREAD

**Issue by OE3GSU** [TwinFan/LiveTraffic#121]
**Current Situation / Problem**
To check how many airplanes LT knows, i have to use the mouse to open the menu. 

**Suggested Solution**
A small "status field" anywhere on the Screen (Menu-point to activate/deactivate?) could show the two numbers (LT knows / displays aircrafts)

**Alternatives**

**Benefits**
Better info about the airplanes around my plane.

**TODO**
- [x] Separate window to open, not widget based, so can use full XP11 feature like moving/popout
- [x] Save last location/status in config
Display:
- [x] number of aircraft displayed/seen in data or OFF
- [x] number of TCAS blibs or OFF
- [x] last update received per channel or OFF
- [x] RealTraffic connection status

**Comment by TwinFan** [comment]
Some people even wanted the message area removed for interference with immersion...others want to be kept updated. Users are different. So it needs to become an option. Or a menu item to be activated.

Probably to be merged with #21 i.e. the creation of a plane list. We could add an option to that listing window to show "title bar only" or something like that, which just show number of displayed and number of seen aircraft.
