### ISSUE TITLE
Ease usage of LiveTraffic and XSB in parallel

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#39]
**Describe the bug**
XSquawkBox (XSB) wants to acquire multiplayer planes during initialization by a call to `XPMPMultiplayerEnable`. In a standard install LiveTraffic (LT) is initialized before XSB, because it is first in the alphabet. Hence, XSB can't acquire the planes as LT has them already.

Even with tricks like disabling/re-enabling the plugins in the plugin admin XSB will never try to re-acquire the multiplayer plugins. So there is no way the access to the multiplayer planes and hence the successful working of the plugins could be handed back and forth between the plugins. This is bad design on the XSB side...let's make it better on the LT side.

So currently recommendation is to move plugins to a `plugins_disabled` folder and have only one of them active in the `plugins` folder. That's cumbersome.

**To Reproduce**
Install both XSquawkBox and LiveTraffic (which is, at least temporarily (see #38), current installation procedure). Fire up X-Plane and watch the Log.txt

```
WARNING: XSquawkBox did not acquire multiplayer planes!!
```

in `Log.txt`.

**Expected behavior**
Some better handling of keeping both plugins in parallel. We can't change XSB, but we should enable to startup X-Plane with XSB working properly and allow a handover to LiveTraffic by disabling XSB in the plugin admin.

**Technical Info:**
 - OS: any
 - X-Plane version: any
 - LiveTraffic version: 0.8.181130

**Todo**

- [x] Delay the call to `XPMPMultiplayerEnable` until `LTMainShowAircraft`.
- [x] Make sure that if LT can't acquire multiplayer planes (because XSB [or X-IvAp for that matter] is still running) this shows up as an error to the user.
- [x] Allow to move LT to any plugin folder like `ZZLiveTraffic` to ensure it starts _after_ XSB. This will mean to change the way we find _our_ resources like the `FileModel.prf` (and the files affected by #38).

**Comment by TwinFan** [comment]
Also made "Reload Plugins" available even in non-debug builds. Only way to get XSquawkBox activated again after once switching to LT.

Documentation updated, but not yet published, including a long section on how to run XSB and LT in parallel and switch between them while X-Plane is running.
