### ISSUE TITLE
New Channel: "Open Glider Network" / "GliderNet"

### ISSUE THREAD

**Issue by TwinFan** [TwinFan/LiveTraffic#72]
**Current Situation / Problem**
Limited GA, no glider coverage in LiveTraffic. GliderNet is not supported as a tracking data channel.

**Suggested Solution**
Support [GliderNet](https://www.glidernet.org/), an open solution.

**Benefits**
A little increase in GA traffic, adding glide traffic.
Would make LiveTraffic interesting also for sailplane / glider sim pilots.

**Additional context**
While there are high-level APIs available they require pretty fat libraries to include, which I'm reluctant to do. However, there seem to be just [standard request/reply possibilities](https://github.com/glidernet/ogn-live#backend), which would fit into the LiveTraffic design.

E.g. http://live.glidernet.org/lxml.php?a=1&b=51.7568&c=47.3490&d=15.0239&e=1.0054&z=2 returns something like
```
<markers>
<m a="48.517132,1.640970,_7a,a90b107a,149,16:41:23,31002,0,0,-0.1,1,LFFL,0,a90b107a"/>
<m a="47.448650,8.209450,SGI,HB-SGI,792,16:41:09,31016,120,178,-3.6,8,Bohlhof,4B302C,991d079d"/>
<m a="49.984921,11.642450,ZG,D-EFZG,476,17:05:53,29532,0,0,0.7,8,EDQD,3D146C,25200416"/>
<m a="50.352421,8.905480,_7e,82b8df7e,349,17:16:03,28922,170,185,-0.2,1,Nidda,0,82b8df7e"/>
<m a="49.602821,7.160050,_af,697429af,508,17:23:29,28476,155,93,-2.7,8,EDRG,0,697429af"/>
<m a="50.061871,11.287950,_00,e5f39900,1107,16:31:33,31592,6,178,1.2,1,EDER,0,e5f39900"/>
<m a="49.601021,8.351350,_59,70bac159,174,17:06:58,29467,63,94,-3.1,2,LuDaN,0,70bac159"/>
...
</markers>
```
**Todos**

- [x] Understand the format and how request/reply works
- [x] Design how the data fits into the LTFlightData model. This is not ICAO defined, we need to map and match it somehow to integrate with the existing LT world.
    - [X] Allow other FD a/c keys than ICAO, e.g. FLARM id
    - [x] Provide mapping from FLARM acft type to CSL models like we did for cars already.
- [x] Might need some adjustments to the flight model...gliders aren't Airbusses
- [x] Last but not least we need one or two reasonable CSL models to represent the found gliders.

**Comment by TwinFan** [comment]
172MC has a glider, downloaded from X-Plane: [ASK21](https://forums.x-plane.org/index.php?/files/file/41335-ask21-ver8-csl/)

**Comment by TwinFan** [comment]
Documentation for request/reply is rather thin. The following I consolidated from various sources:

A valid request is as stated [here](https://github.com/glidernet/ogn-live#ajax-endpoints):
```
http://live.glidernet.org/lxml.php?a=1&b=51.7568&c=47.3490&d=15.0239&e=1.0054&z=2
```

The [Python source code of an alternative OGN backend](https://github.com/Meisterschueler/ogn-live-backend/blob/master/livebackend.py) (the server answering the requests) gives away details of the request and reply format.
- Request Format
```
show_offline = request.args.get('a', 0, type=int) == 1
    lat_max = request.args.get('b', 90, type=int)
    lat_min = request.args.get('c', -90, type=int)
    lon_max = request.args.get('d', 180, type=int)
    lon_min = request.args.get('e', -180, type=int)
```
And by trial and error I assume that `z` is a timezone to which the timestamps are to be converted. As LiveTraffic prefers ZULU/GMT anyway we just leave it out.

- Reply Format
```
lines.append('<m a="{0:.7f},{1:.7f},{2},{3},{4},{5},{6},{7},{8},{9},{10},{11},{12},{13}"/>'
                     .format(aircraft_beacon.location.latitude,
                             aircraft_beacon.location.longitude,
                             competition,
                             registration,
                             aircraft_beacon.altitude,
                             utc_to_local(aircraft_beacon.timestamp).strftime("%H:%M:%S"),
                             elapsed_seconds,
                             int(aircraft_beacon.track),
                             int(aircraft_beacon.ground_speed),
                             int(aircraft_beacon.climb_rate*10)/10,
                             aircraft_beacon.aircraft_type,
                             aircraft_beacon.receiver_name,
                             address,
                             code))
```

Aircraft type is likely the FLARM type, field `ACFT` as in the [FLARM specs](http://ediatec.ch/pdf/FTD-014-FLARM-Configuration-Specification.pdf).

- [ ] Provide mapping from FLARM acft type to CSL models like we did for cars already.

**Comment by TwinFan** [comment]
Sent a mail to `contact [at] glidernet.org`, asking permission to use the data.
